name: weather_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  fpdart: ^1.1.0
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  go_router: ^14.2.7
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed_annotation: ^2.4.4
  very_good_analysis: ^5.1.0
  device_preview: ^1.1.0
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/
